# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-18 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 18, 13, 59, 48, 277860)),
        ),
    ]
